language: python
python:
- '3.6'
install:
  - pip install -r requirements.txt
env:
  -testing = True
services:
  - postgresql
before_script:
  - psql -c "create database sendIT;" -U postgres
  # - export APP_SETTINGS=testing  

addons:
  postgresql: "9.4"
script:
  - pytest --cov=.
  - coverage
  - coveralls
  - coverage report
after_success:
  - coveralls